# -*- coding: utf-8 -*-
"""Bank Loan Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVav5ov8p9XABE0S_jqar_PzERR8T2PD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# LOAD DATA
df = pd.read_csv("financial_loan_data.csv")

print("Dataset loaded successfully!")
print(df.head())

# BASIC CLEANING

# Convert dates to proper datetime format
df["issue_date"] = pd.to_datetime(df["issue_date"], errors="coerce")

# Fill missing numeric values with median
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# Fill missing categorical values with "Unknown"
categorical_cols = df.select_dtypes(include=["object"]).columns
df[categorical_cols] = df[categorical_cols].fillna("Unknown")

print("\nMissing values handled!")

# FEATURE ENGINEERING

df["year"] = df["issue_date"].dt.year
df["month"] = df["issue_date"].dt.month_name()
df["month_number"] = df["issue_date"].dt.month

# Utilization = loan_amount / annual_income
df["utilization"] = df["loan_amount"] / (df["annual_income"] + 1)

print("\nFeature engineering completed!")

# OVERALL KPIs

def calculate_kpis(data):
    return {
        "Total Loan Applications": len(data),
        "Total Funded Amount": data["loan_amount"].sum(),
        "Total Amount Received": data["total_payment"].sum(),
        "Average Interest Rate (%)": round(data["int_rate"].mean() * 100, 2),
        "Average DTI (%)": round(data["dti"].mean() * 100, 2)
    }

overall_kpis = calculate_kpis(df)

print("\n--- OVERALL KPIs ---")
for k, v in overall_kpis.items():
    print(f"{k}: {v:,}")

# MTD AND PMTD KPIs (December vs November 2021)

mtd = df[(df["year"] == 2021) & (df["month_number"] == 12)]
pmtd = df[(df["year"] == 2021) & (df["month_number"] == 11)]

print("\n--- DECEMBER 2021 KPIs ---")
print(calculate_kpis(mtd))

print("\n--- NOVEMBER 2021 KPIs ---")
print(calculate_kpis(pmtd))

# 6. GOOD LOAN / BAD LOAN ANALYSIS

good_status = ["Fully Paid", "Current"]
bad_status = ["Charged Off"]

df["loan_type"] = np.where(
    df["loan_status"].isin(good_status), "Good Loan",
    np.where(df["loan_status"].isin(bad_status), "Bad Loan", "Other")
)

good_loans = df[df["loan_type"] == "Good Loan"]
bad_loans = df[df["loan_type"] == "Bad Loan"]

good_loan_kpis = {
    "Good Loan %": round((len(good_loans) / len(df)) * 100, 2),
    "Good Loan Applications": len(good_loans),
    "Good Loan Funded Amount": good_loans["loan_amount"].sum(),
    "Good Loan Received Amount": good_loans["total_payment"].sum()
}

bad_loan_kpis = {
    "Bad Loan %": round((len(bad_loans) / len(df)) * 100, 2),
    "Bad Loan Applications": len(bad_loans),
    "Bad Loan Funded Amount": bad_loans["loan_amount"].sum(),
    "Bad Loan Received Amount": bad_loans["total_payment"].sum()
}

print("\n--- GOOD LOAN KPIs ---")
print(good_loan_kpis)

print("\n--- BAD LOAN KPIs ---")
print(bad_loan_kpis)

# GROUP-BY ANALYSIS (Matches your SQL)

# Loan Status Breakdown
loan_status_summary = df.groupby("loan_status").agg(
    Loan_Count=("id", "count"),
    Total_Amount_Received=("total_payment", "sum"),
    Total_Funded_Amount=("loan_amount", "sum"),
    Interest_Rate=("int_rate", lambda x: round(x.mean() * 100, 2)),
    DTI=("dti", lambda x: round(x.mean() * 100, 2))
).reset_index()

print("\n--- LOAN STATUS SUMMARY ---")
print(loan_status_summary)

# State-Level Summary
state_summary = df.groupby("address_state").agg(
    Applications=("id", "count"),
    Funded_Amount=("loan_amount", "sum"),
    Received_Amount=("total_payment", "sum")
).sort_values("Received_Amount", ascending=False)
print("\n--- STATE SUMMARY ---")
print(state_summary.head())

# Term Summary
term_summary = df.groupby("term").agg(
    Applications=("id", "count"),
    Funded_Amount=("loan_amount", "sum"),
    Received_Amount=("total_payment", "sum")
)
print("\n--- TERM SUMMARY ---")
print(term_summary)

# Employment Length Summary
emp_summary = df.groupby("emp_length").agg(
    Applications=("id", "count"),
    Funded_Amount=("loan_amount", "sum"),
    Received_Amount=("total_payment", "sum")
).sort_values("Applications", ascending=False)
print("\n--- EMPLOYMENT LENGTH SUMMARY ---")
print(emp_summary)

# Purpose Summary
purpose_summary = df.groupby("purpose").agg(
    Applications=("id", "count"),
    Funded_Amount=("loan_amount", "sum"),
    Received_Amount=("total_payment", "sum")
).sort_values("Applications", ascending=False)
print("\n--- PURPOSE SUMMARY ---")
print(purpose_summary)

# VISUALIZATIONS

plt.figure(figsize=(7, 5))
df["loan_status"].value_counts().plot(kind="bar")
plt.title("Loan Status Distribution")
plt.xlabel("Loan Status")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("loan_status_distribution.png")

print("\nVisualization saved: loan_status_distribution.png")

# EXPORT CLEANED DATA & KPI OUTPUTS

df.to_csv("cleaned_financial_loan_data.csv", index=False)
loan_status_summary.to_csv("kpi_loan_status.csv", index=False)
state_summary.to_csv("kpi_state_summary.csv")
purpose_summary.to_csv("kpi_purpose_summary.csv")

print("\nAll outputs exported successfully!")